### ISSUE TITLE
Review des Visions-Dokument

### ISSUE THREAD

**Issue by juliusschramm** [sebastiantress03/Projekt-Software-Engineering#12]
Ich bitte alle, das Visions-Dokument bis **spät. Montag, den 25.11.2024** durchzulesen und Verbesserungsvorschläge / Kritikpunkte dazu zu äußern.
**Diese sind bitte zu diesem Issue zu kommentieren!** Falls ihr es durchgelesen habt, bitte abhaken.
Besprechung darüber erfolgt dann am Meeting am Montag.

- [x] Sebastian
- [ ] Luke
- [x] Niklas
- [x] Louai
- [x] Tom

**Comment by Loay-99** [comment]
Bei der Benutzerumgebung habe ich letztens mit Herrn Anke darüber gesprochen. Er meinte man kann es von mehreren Sichten betrachten.

In unserem Fall kann man die Benutzerumgebung von Sicht des Sturas und Spielers betrachten.

**Comment by niklas-benjamin-grosse** [comment]
Momentan stören mich nur ein paar Schreibfehler, darf ich die ohne Review committen?
Wäre dafür ja eig ein bisschen übertrieben.
