### ISSUE TITLE
Schnittstelle Datenbank und Back End und Recherche über Datenbanken

### ISSUE THREAD

**Issue by juliusschramm** [sebastiantress03/Projekt-Software-Engineering#40]
**Generierung von Wissen über Schnittstellen innerhalb von Datenbanken in Verbindung mit Python**

Vorstellen des erarbeiteten Wissens im Meeting

_!noch keine Programmierung!_

### DoD:

- [x] Verschiedene Datenbankschnittstellen wurden erkannt und erklärt
- [x] Vor - und Nachteile zu den jeweiligen rausschreiben
- [x] Unterschied SQL und NoSQL
- [x] Python-Bibliotheken recherchieren
- [ ] Vorstellung der Datenbanksystemoptionen

**Comment by niklas-benjamin-grosse** [comment]
Bereit für die Vorstellung am Montag
